=== adolforestrepo/test-repo/taxonomy/xml/taxonomy.dtd
<!-- **** RSuite Elements **** -->

<!ENTITY % rsuite-meta "(RSUITE:METADATA?)" >

<!ENTITY % rsuite-namespace-attr "xmlns:RSUITE CDATA 'http://www.reallysi.com'" >

<!ENTITY % rsuite-metadata-elements "(RSUITE:ELEMENTNAME | RSUITE:SOURCEID | 
RSUITE:CREATEDATE | RSUITE:LASTMODIFIED | RSUITE:CHECKOUT | RSUITE:ID | 
RSUITE:USER | RSUITE:FOLDER | RSUITE:DISPLAYNAME | RSUITE:SOURCE-ELEMENT | 
RSUITE:CHECKOUTDATETIME )*" >

<!ELEMENT RSUITE:CROSSREF (RSUITE:METADATA) >
<!ATTLIST RSUITE:CROSSREF %rsuite-namespace-attr; >

<!ELEMENT RSUITE:INCLUDE (RSUITE:METADATA) >
<!ATTLIST RSUITE:INCLUDE %rsuite-namespace-attr; >

<!ELEMENT RSUITE:METADATA (RSUITE:SYSTEM|RSUITE:SOURCE|RSUITE:LAYERED)* >
<!ATTLIST RSUITE:METADATA %rsuite-namespace-attr; >

<!ELEMENT RSUITE:SYSTEM (%rsuite-metadata-elements;) >
<!ATTLIST RSUITE:SYSTEM %rsuite-namespace-attr; >

<!ELEMENT RSUITE:SOURCE (%rsuite-metadata-elements;) >
<!ATTLIST RSUITE:SOURCE %rsuite-namespace-attr; >

<!ELEMENT RSUITE:LAYERED (RSUITE:DATA)* >
<!ATTLIST RSUITE:LAYERED %rsuite-namespace-attr; >

<!ELEMENT RSUITE:ID (#PCDATA) >
<!ATTLIST RSUITE:ID %rsuite-namespace-attr; >

<!ELEMENT RSUITE:SOURCEID (#PCDATA) >
<!ATTLIST RSUITE:SOURCEID %rsuite-namespace-attr; >

<!ELEMENT RSUITE:SOURCE-ELEMENT (#PCDATA) >
<!ATTLIST RSUITE:SOURCE-ELEMENT %rsuite-namespace-attr; >

<!ELEMENT RSUITE:CREATEDATE (#PCDATA) >
<!ATTLIST RSUITE:CREATEDATE %rsuite-namespace-attr; >

<!ELEMENT RSUITE:ELEMENTNAME (#PCDATA) >
<!ATTLIST RSUITE:ELEMENTNAME %rsuite-namespace-attr; >

<!ELEMENT RSUITE:LASTMODIFIED (#PCDATA) >
<!ATTLIST RSUITE:LASTMODIFIED %rsuite-namespace-attr; >

<!ELEMENT RSUITE:FOLDER (#PCDATA) >
<!ATTLIST RSUITE:FOLDER %rsuite-namespace-attr; >

<!ELEMENT RSUITE:USER (#PCDATA) >
<!ATTLIST RSUITE:USER %rsuite-namespace-attr; >

<!ELEMENT RSUITE:CHECKOUT (#PCDATA) >
<!ATTLIST RSUITE:CHECKOUT %rsuite-namespace-attr; >

<!ELEMENT RSUITE:CHECKOUTDATETIME (#PCDATA) >
<!ATTLIST RSUITE:CHECKOUTDATETIME %rsuite-namespace-attr; >

<!ELEMENT RSUITE:DISPLAYNAME (#PCDATA) >
<!ATTLIST RSUITE:DISPLAYNAME RSUITE:AUTOGENERATE CDATA #IMPLIED
  %rsuite-namespace-attr; >

<!ELEMENT RSUITE:DATA (#PCDATA) >
<!ATTLIST RSUITE:DATA %rsuite-namespace-attr;
  RSUITE:NAME CDATA #IMPLIED >
 
 <!-- Taxonomy elements --> 
<!ELEMENT taxonomy (%rsuite-meta;,taxonomy-options+)>

<!ELEMENT taxonomy-options (%rsuite-meta;,taxonomy-option+)>
<!ATTLIST taxonomy-options name CDATA #REQUIRED>

<!ELEMENT taxonomy-option (synonym*,taxonomy-children?)>
<!ATTLIST taxonomy-option name CDATA #IMPLIED>
<!ATTLIST taxonomy-option value CDATA #REQUIRED>
<!ATTLIST taxonomy-option selectable CDATA #IMPLIED>

<!ELEMENT taxonomy-children (taxonomy-option+)>

<!ELEMENT synonym (#PCDATA)>

=== adolforestrepo/test-repo/taxonomy/xml/taxonomy.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE taxonomy PUBLIC "urn:pubid:astd.com:doctypes:taxonomy" "taxonomy.dtd">
<taxonomy>
   <taxonomy-options name="Research">
      <taxonomy-option value="methods"/>
      <taxonomy-option value="efficacy"/>
      <taxonomy-option value="efficiency"/>
      <taxonomy-option value="delivery systems"/>
      <taxonomy-option value="cognitive"/>
      <taxonomy-option value="affective"/>
      <taxonomy-option value="psychomotor"/>
   </taxonomy-options>
   <taxonomy-options name="Point of View">
      <taxonomy-option value="Trainers"/>
      <taxonomy-option value="Researchers"/>
      <taxonomy-option value="Learners"/>
      <taxonomy-option value="Other"/>
   </taxonomy-options>
   <taxonomy-options name="Delivery Method">
      <taxonomy-option value="Conference"/>
      <taxonomy-option value="Classroom"/>
      <taxonomy-option value="Workshop"/>
      <taxonomy-option value="Web (computer)"/>
      <taxonomy-option value="Web (mobile/pda)"/>
      <taxonomy-option value="Webinar"/>
      <taxonomy-option value="Online Classes"/>
      <taxonomy-option value="Mail"/>
      <taxonomy-option value="Conference Call"/>
      <taxonomy-option value="Video"/>
      <taxonomy-option value="Audio"/>
   </taxonomy-options>
   <taxonomy-options name="Delivery Format">
      <taxonomy-option value="Books"/>
      <taxonomy-option value="Magazines"/>
      <taxonomy-option value="Periodicals"/>
      <taxonomy-option value="Training Series"/>
      <taxonomy-option value="Reports"/>
      <taxonomy-option value="Flyers"/>
      <taxonomy-option value="Downloadable"/>
      <taxonomy-option value="Streaming"/>
      <taxonomy-option value="On-demand"/>
      <taxonomy-option value="Whitepaper"/>
   </taxonomy-options>
   <taxonomy-options name="Distribution Frequency">
      <taxonomy-option value="Daily"/>
      <taxonomy-option value="Weekly"/>
      <taxonomy-option value="Monthly"/>
      <taxonomy-option value="Quarterly"/>
      <taxonomy-option value="Yearly"/>
      <taxonomy-option value="Irregular"/>
      <taxonomy-option value="Other"/>
      <taxonomy-option value="Once"/>
   </taxonomy-options>
   <taxonomy-options name="Audience">
      <taxonomy-option value="Trainers"/>
      <taxonomy-option value="Researchers"/>
      <taxonomy-option value="Learners"/>
      <taxonomy-option value="Others"/>
   </taxonomy-options>
   <taxonomy-options name="Certification">
      <taxonomy-option value="Certification Level">
         <taxonomy-children>
            <taxonomy-option value="[none]"/>
         </taxonomy-children>
      </taxonomy-option>
      <taxonomy-option value="Certification Organization">
         <taxonomy-children>
            <taxonomy-option value="[none]"/>
         </taxonomy-children>
      </taxonomy-option>
      <taxonomy-option value="Certification Recognized By">
         <taxonomy-children>
            <taxonomy-option value="[none]"/>
         </taxonomy-children>
      </taxonomy-option>
   </taxonomy-options>
   <taxonomy-options name="Level of Expertise">
      <taxonomy-option value="Beginner"/>
      <taxonomy-option value="Intermediate"/>
      <taxonomy-option value="Advanced"/>
   </taxonomy-options>
   <taxonomy-options name="Affiliation with Training Organizations">
      <taxonomy-option value="ASTD"/>
      <taxonomy-option value="eLearning Guild"/>
      <taxonomy-option value="TRAINAIR"/>
   </taxonomy-options>
   <taxonomy-options name="Affiliation with Industry Organizations">
      <taxonomy-option value="Automotive"/>
      <taxonomy-option value="Technology"/>
      <taxonomy-option value="Trade Unions"/>
      <taxonomy-option value="Aviation"/>
   </taxonomy-options>
   <taxonomy-options name="Affiliation with Higher Education Organizations">
      <taxonomy-option value="University of Maryland"/>
   </taxonomy-options>
   <taxonomy-options name="Affiliation with Foundations">
      <taxonomy-option value="Foundation and Institute"/>
      <taxonomy-option value="Brookings Institute"/>
      <taxonomy-option value="PNAC"/>
   </taxonomy-options>
   <taxonomy-options name="Affiliation with Government Organizations">
      <taxonomy-option value="County"/>
      <taxonomy-option value="State"/>
      <taxonomy-option value="Municipal"/>
      <taxonomy-option value="Pan-national"/>
   </taxonomy-options>
   <taxonomy-options name="Industry">
      <taxonomy-option value="Accounting/Auditing/Underwriting Industry"/>
      <taxonomy-option value="Associations &amp; Nonprofit Organizations"/>
      <taxonomy-option value="Automotive Industry"/>
      <taxonomy-option value="Aviation &amp; Space Industry"/>
      <taxonomy-option value="Beverage Brewing &amp; Bottling Industry"/>
      <taxonomy-option value="Chemicals &amp; Pharmaceutical Industry"/>
      <taxonomy-option value="Communications, Publications, &amp; Broadcasting Industry"/>
      <taxonomy-option value="Construction Industry"/>
      <taxonomy-option value="Criminal Justice Systems"/>
      <taxonomy-option value="Education Institutions"/>
      <taxonomy-option value="Electronics Industry"/>
      <taxonomy-option value="Financial Services Industry"/>
      <taxonomy-option value="Food Industries"/>
      <taxonomy-option value="Government (National)"/>
      <taxonomy-option value="Government (Regional/Local)"/>
      <taxonomy-option value="Healthcare Industry"/>
      <taxonomy-option value="Hospitality Industry"/>
      <taxonomy-option value="Information Technology Industry"/>
      <taxonomy-option value="Insurance Industry"/>
      <taxonomy-option value="Manufacturing/Industrial Industry"/>
      <taxonomy-option value="Military"/>
      <taxonomy-option value="Mining/Energy/Natural Resources"/>
      <taxonomy-option value="Petroleum &amp; Natural Gas Industry"/>
      <taxonomy-option value="Professional/Consulting Services"/>
      <taxonomy-option value="Real Estate Industry"/>
      <taxonomy-option value="Recreation/Amusement Industry"/>
      <taxonomy-option value="Retail Industry"/>
      <taxonomy-option value="Service Industries"/>
      <taxonomy-option value="Technology Industry"/>
      <taxonomy-option value="Telecommunications Industry"/>
      <taxonomy-option value="Textiles Industry"/>
      <taxonomy-option value="Transportation Industry"/>
      <taxonomy-option value="Utilities Industry"/>
   </taxonomy-options>
   <taxonomy-options name="Country">
      <taxonomy-option value="North America" selectable="false">
         <taxonomy-children>
            <taxonomy-option value="USA"/>
            <taxonomy-option value="Mexico"/>
            <taxonomy-option value="Canada"/>
         </taxonomy-children>
      </taxonomy-option>
      <taxonomy-option value="Central America" selectable="false">
         <taxonomy-children>
            <taxonomy-option value="Belize"/>
            <taxonomy-option value="Costa Rica"/>
            <taxonomy-option value="El Salvador"/>
            <taxonomy-option value="Guatemala"/>
            <taxonomy-option value="Honduras"/>
            <taxonomy-option value="Nicaragua"/>
            <taxonomy-option value="Panama"/>
         </taxonomy-children>
      </taxonomy-option>
      <taxonomy-option value="South America" selectable="false">
         <taxonomy-children>
            <taxonomy-option value="Argentina"/>
            <taxonomy-option value="Bolivia"/>
            <taxonomy-option value="Brazil"/>
            <taxonomy-option value="Chile"/>
            <taxonomy-option value="Colombia"/>
            <taxonomy-option value="Ecuador"/>
            <taxonomy-option value="Falkland Islands (UK)"/>
            <taxonomy-option value="French Guiana"/>
            <taxonomy-option value="Guyana"/>
            <taxonomy-option value="Paraguay"/>
            <taxonomy-option value="Peru"/>
            <taxonomy-option value="Suriname"/>
            <taxonomy-option value="Uruguay"/>
            <taxonomy-option value="Venezuela"/>
         </taxonomy-children>
      </taxonomy-option>
      <taxonomy-option value="Europe" selectable="false">
         <taxonomy-children>
            <taxonomy-option value="Albania"/>
            <taxonomy-option value="Andorra"/>
            <taxonomy-option value="Armenia"/>
            <taxonomy-option value="Austria"/>
            <taxonomy-option value="Azerbaijan"/>
            <taxonomy-option value="Belarus"/>
            <taxonomy-option value="Belgium"/>
            <taxonomy-option value="Bosnia and Herzegovina"/>
            <taxonomy-option value="Bulgaria"/>
            <taxonomy-option value="Croatia"/>
            <taxonomy-option value="Cyprus"/>
            <taxonomy-option value="Czechia"/>
            <taxonomy-option value="Denmark"/>
            <taxonomy-option value="Estonia"/>
            <taxonomy-option value="Finland"/>
            <taxonomy-option value="France"/>
            <taxonomy-option value="Georgia"/>
            <taxonomy-option value="Germany"/>
            <taxonomy-option value="Greece"/>
            <taxonomy-option value="Holy See"/>
            <taxonomy-option value="Hungary"/>
            <taxonomy-option value="Iceland"/>
            <taxonomy-option value="Ireland"/>
            <taxonomy-option value="Italy"/>
            <taxonomy-option value="Kazakhstan"/>
            <taxonomy-option value="Latvia"/>
            <taxonomy-option value="Liechtenstein"/>
            <taxonomy-option value="Lithuania"/>
            <taxonomy-option value="Luxembourg"/>
            <taxonomy-option value="Macedonia"/>
            <taxonomy-option value="Malta"/>
            <taxonomy-option value="Moldova"/>
            <taxonomy-option value="Monaco"/>
            <taxonomy-option value="Montenegro"/>
            <taxonomy-option value="Netherlands"/>
            <taxonomy-option value="Norway"/>
            <taxonomy-option value="Poland"/>
            <taxonomy-option value="Portugal"/>
